spring:
  application:
    name: distributed-transaction
  rabbitmq:
    host: 127.0.0.1
  redis:
    timeout: 0
    host: 127.0.0.1
    database: 0
  datasource:
    url: jdbc:mysql://10.19.165.89:4000/shine?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: hikvision
    password: hikvision
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
server:
  port: 3000
  undertow:
    accesslog:
      dir: /logs              # Undertow 日志存放目录
      enabled: true           # 是否启动日志
      pattern: common         # 日志格式
      prefix: access_log      # 日志文件名前缀
      suffix: log             # 日志文件名后缀
    max-http-post-size: 0     # HTTP POST请求最大的大小
    io-threads: 4             # 设置IO线程数，它主要执行非阻塞的任务，它们会负责多个连接，默认设置每个CPU核心一个线程
    worker-threads: 500       # 阻塞任务线程池，当执行类似servlet请求阻塞操作，undertow会从这个线程池中取得线程，它的值设置取决于系统的负载
    buffer-size: 1024         # 以下的配置会影响buffer，这些buffer会用于服务器连接的IO操作,每块buffer的空间大小，越小的空间被利用越充分
    direct-buffers: true      # 是否分配的直接内存
shine:
  mq:
    distributed:
      transaction: true
